### PR TITLE
Changes for Kurdish

### PR DESCRIPTION
**Pull request by Shreeshrii**
kur - removed (copy exists as kur_ara)
kmr - copied from langdata_lstm

### CODE REVIEW

**Comment by Shreeshrii** [comment]
@stweil Please review.

**Comment by amitdo** [comment]
The text is too long for the legacy engine.

**Comment by Shreeshrii** [comment]
That's right. I will create a small sample.

On 3/15/19, Amit D. <notifications@github.com> wrote:
> The text is too long for the legacy engine.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tesseract-ocr/langdata/pull/140#issuecomment-473366778


-- 

____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
Done. Thanks @amitdo

**Pull request merged**
