### PR TITLE
Add ï to desired English characters

### PR DESCRIPTION
**Pull request by stweil**
It is used in naïve, for example.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by amitdo** [comment]
It the first time I see this form of 'naive', and also the first time to see 'ï' being used in English.

**Comment by amitdo** [comment]
https://en.wiktionary.org/wiki/Category:English_terms_spelled_with_%C3%8F

**Comment by stweil** [comment]
So you found more examples. :-) I did not know this usage until last week.

**Comment by stweil** [comment]
@zdenop, can this pull request be merged finally?

**Comment by zdenop** [comment]
Sure.

**Pull request merged**
