### PR TITLE
Fix some wrong German words (confusion B / ß)

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by Wikinaut** [comment]
@stweil Stefan, when the tesseract-ocr/langdata is updated, this does not mean that the /tessdata is updated, as far as I know.

As your recent patches are very important for DE language (and would save me from publishing my post-filter `sed` script which is still needed to repair German-ocr-ed texts), please can you take care that the deu*.traineddata files are updated (retrained) as well ?

**Comment by stweil** [comment]
Yes, fixes in langdata need additional work to result in updates of tessdata.

I'm afraid that I cannot do much there. See [another comment](https://github.com/tesseract-ocr/tesseract/issues/707#issuecomment-286373952) which I have just written.

To summarize, tessdata updates for Tesseract 3.x are manageable for contributors like me, but updates for Tesseract 4.x with LSTM are much more difficult. @theraysmith recently announced that he is going to start the training for an update of tessdata with an improved training process, and I hope that this is sufficient to fix some of the problems which we see for German texts (although I am not sure about that, see also the [tesseract-dev forum](https://groups.google.com/forum/#!topic/tesseract-dev/8H_4K3vPRJE)).

**Comment by Shreeshrii** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/wQ8AUCkvDbo/QQJ91biKAAAJ

> Very often tesseract detects "StraBe" instead of "Straße".

>Yes, I use -l=deu

**Comment by stweil** [comment]
Ray did not use the fixed dictionary when he created the LSTM traineddata files, but used new dictionaries with the old (and additional new) errors.

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tessdata/issues/62#issuecomment-319839971

**Comment by guettli** [comment]
@stweil you said that improving the ocr result is harder with 4.0. What does "harder" mean?

I can provide a lot of german scan input which has broken results.

If training material is needed, just tell me.

I could provide parts of scans where a single german word is visible and the corresponding word in utf8.

**Comment by Wikinaut** [comment]
I am sorry to drop in here, but please have a look to the proposal (not a solution, yet) https://github.com/tesseract-ocr/tesseract/issues/1442 [Suggestion] "Training light" - Learning by doing - re-feeding a corrected text file to retrain tesseract.

**Pull request merged**
